# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-30 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Blog_Image', models.ImageField(blank=True, null=True, upload_to=myapp.models.upload_location)),
            ],
        ),
    ]
