# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-30 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Blog_Image',
            new_name='Post_Image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Blog_Name',
            new_name='Post_Name',
        ),
    ]
